{{- if .Values.dockerHub.login }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerhubcreds
  labels:
    app: {{ template "octopus.name" . }}
    chart: {{ template "octopus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  .dockerconfigjson: {{.Values.dockerHub.creds}}
type: kubernetes.io/dockerconfigjson
{{- end }}