{{- if .Values.octopus.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "octopus.name" . }}
    chart: {{ template "octopus.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "octopus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "octopus.serviceAccountName" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "octopus.fullname" . }}
{{- end }}