{{- if .Values.octopus.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- with .Values.octopus.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml .) $ | indent 4 }}
{{- end }}
  labels:
    app: {{ template "octopus.name" . }}
    chart: {{ template "octopus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.octopus.serviceAccount.labels }}
  {{ toYaml .Values.octopus.serviceAccount.labels | indent 2 }}
  {{- end }}
  name: {{ template "octopus.serviceAccountName" . }}
automountServiceAccountToken: {{ .Values.octopus.serviceAccount.automountServiceAccountToken }}
{{- end }}

