apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      # namespace: testing
      labels:
        app: {{ .Release.Name }}
        environment: testing
    spec:
      containers: 
        - image: {{ .Values.image }}
          name: {{ .Release.Name }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
      imagePullSecrets:
        - name: hub-spa