apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector: 
    app: {{ .Release.Name }}
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: {{ .Values.nodePort }}